### ISSUE TITLE
Trying this on BBB running Debian 10 I get Remote I//O error

### ISSUE THREAD

**Issue by chrisisbd** [MilesBDyson/I2C-LCD#2]
I have a pretty standard 'out of the box' BBB with Debian 10 installed.  I get the following error:-
```
chris@odinfb$ ./lcd_i2c.py
Traceback (most recent call last):
  File "./lcd_i2c.py", line 101, in <module>    main()
  File "./lcd_i2c.py", line 82, in main    lcd_init()
  File "./lcd_i2c.py", line 35, in lcd_init    lcd_byte(0x33,LCD_CMD) # 110011 Initialise
  File "./lcd_i2c.py", line 53, in lcd_byte    bus.write_byte(I2C_ADDR, bits_high)
OSError: [Errno 121] Remote I/O error
```
Running the clock.py example produces exactly the same error.  I've checked the wiring  pretty thoroughly and the LCD powers up OK.

What am I doing wrong?  Do I have to do anything to the BBB to enable I2C?  Should I be using a different image?  I can move to Debian 11 easily enough.

Help!    :-)

**Comment by chrisisbd** [comment]
It's OK, me being very silly, I hadn't set the right I2C address.  All working now, thank you very much, it's so simple! :-)
